using System.Diagnostics;
using System.IO;
using System.IO.Pipes;
using System.Text.Json;
using System.Windows;
using Microsoft.Win32;
using Watchblock.Core;
using Watchblock.Windows;
namespace Watchblock.App;
public partial class MainWindow:Window {
 private ApiClient? api;private ClaimResponse? claim;private ScanReport? report;private CancellationTokenSource? cts;private bool working;private bool terminal;private System.Windows.Threading.DispatcherTimer? heartbeat;private int inspected;private bool reporting;
 public MainWindow(){Theme.Load();InitializeComponent();ThemeToggle.Content=Theme.IsLight?"☾  다크 모드":"☼  화이트 모드";SourceInitialized+=(_,_)=>Theme.TitleBar(this);InitializeFlow();Closing+=(_,e)=>{if(working){cts?.Cancel();e.Cancel=true;Status.Text="작업 취소 중입니다. 완료 후 창을 닫아 주세요.";}else api?.Dispose();};}
 private void Busy(bool value){if(value){ProgressPercent.Text="";ProgressEta.Text="";}working=value;ScanActivity.Visibility=value?Visibility.Visible:Visibility.Collapsed;ScanActivity.IsIndeterminate=value;Setup.IsEnabled=!value;ScanButton.IsEnabled=!value&&!terminal&&claim!=null&&report==null;CancelButton.IsEnabled=value;SubmitButton.IsEnabled=!value&&!terminal&&report!=null&&claim!=null;ExportButton.IsEnabled=!value&&report!=null;DeclineButton.IsEnabled=!value&&!terminal&&claim!=null;RefreshFlow();}
 private async void Connect_Click(object sender,RoutedEventArgs e){try{var invitation=Invitation.Parse(Code.Text,Server.Text);Server.Text=invitation.Origin;ProgressTitle.Text="검사 요청을 확인합니다";ProgressCount.Text="운영자 서버 연결 중";Busy(true);var next=new ApiClient(invitation.Origin);try{var health=await next.Send<JsonElement>("GET","/api/health");if(!health.TryGetProperty("schemaVersion",out var schema)||schema.GetInt32()!=1)throw new InvalidOperationException("서버와 앱의 버전이 맞지 않습니다. 최신 설치 파일을 받아 주세요.");if(health.TryGetProperty("ready",out var ready)&&!ready.GetBoolean())throw new InvalidOperationException("운영자가 아직 서버 설정을 완료하지 않았습니다.");var result=await next.Send<ClaimResponse>("POST","/api/claim",new{code=invitation.Code,capabilities=new[]{"all-files","hardware-changes"}});if(result.Origin!=next.Origin)throw new InvalidOperationException("서비스 주소와 응답의 수신 주소가 다릅니다.");api?.Dispose();api=next;claim=result;api.Token=result.Token;report=null;terminal=false;DeleteButton.IsEnabled=false;ScanButton.IsEnabled=true;Roots.Items.Clear();Files.ItemsSource=null;Findings.ItemsSource=null;Artifacts.ItemsSource=null;Coverage.ItemsSource=null;Options.IsEnabled=true;ConnectedService.Text=result.Service;var minecraft=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),".minecraft");if(result.Session.Scope.AllFiles&&Directory.Exists(SystemRoot))Roots.Items.Add(SystemRoot);else if(Directory.Exists(minecraft))Roots.Items.Add(minecraft);RecommendedButton.Visibility=result.Session.Scope.AllFiles?Visibility.Visible:Visibility.Collapsed;ConnectionPanel.IsExpanded=false;Consent.IsChecked=false;Elevate.IsEnabled=result.Session.Scope.ExecutionTraces;DeletedHistory.IsEnabled=result.Session.Scope.ExecutionTraces;DeletedHistory.IsChecked=result.Session.Scope.ExecutionTraces;AddDrivesButton.Visibility=result.Session.Scope.AllFiles?Visibility.Visible:Visibility.Collapsed;ScopeDescription.Text=result.Session.Scope.AllFiles?"권장: C 드라이브 · 숨김 파일 포함, 선택한 제외 적용":"선택 폴더의 실행 파일·모드·리소스팩 검사";SessionInfo.Text=$"{result.Service} · {result.Operator}\n대상: {result.Session.Nickname}\n사유: {result.Session.Reason}";ConsentInfo.Text=$"수신: {api.Origin}\n파일 목록·해시·탐지 근거{(result.Session.Scope.ExecutionTraces?"·관련 실행 흔적(선택 시 휴지통·삭제 기록 포함)":"")} 전송. 개인 경로 마스킹, 파일 원본 제외. 7일 보관. 제출 전에 결과를 확인합니다."+(result.Session.Scope.AllFiles?"\n전체 파일 검사: 문서·이미지 등도 파일명·해시를 공유합니다. 파일 내용은 전송하지 않습니다.":"")+(result.Session.Scope.HardwareChanges?"\n시스템 변경 검사: 로컬 식별값 해시 기준과 비교. 원본 식별값은 전송하지 않습니다.":"");Status.Text="폴더 선택 → 동의 → 검사 시작 순서로 진행해 주세요.";}catch{next.Dispose();throw;}}catch(Exception ex){Status.Text=ex.Message;}finally{Busy(false);}}
 private void AddFolder_Click(object sender,RoutedEventArgs e){try{if(claim==null)return;if(!claim.Session.Scope.GameFiles&&!claim.Session.Scope.ExtraFolders&&!claim.Session.Scope.AllFiles){Status.Text="이 검사는 실행 흔적만 요청했습니다. 연결할 게임 폴더를 선택할 수 있습니다.";}if(Roots.Items.Count>=10)throw new InvalidOperationException("최대 10개 폴더를 선택할 수 있습니다.");if(Roots.Items.Count>0&&!claim.Session.Scope.ExtraFolders&&!claim.Session.Scope.AllFiles)throw new InvalidOperationException("추가 폴더 검사가 허용되지 않은 요청입니다.");var dialog=new OpenFolderDialog{Title="Minecraft 인스턴스 또는 동의할 추가 검사 폴더"};if(dialog.ShowDialog(this)==true&&!Roots.Items.Contains(dialog.FolderName)){Roots.Items.Add(dialog.FolderName);Consent.IsChecked=false;}RefreshFlow();}catch(Exception ex){Status.Text=ex.Message;}}
 private void RemoveFolder_Click(object sender,RoutedEventArgs e){if(Roots.SelectedItem is object item){Roots.Items.Remove(item);Consent.IsChecked=false;}RefreshFlow();}
 private async void Scan_Click(object sender,RoutedEventArgs e){if(api==null||claim==null)return;try{if(Consent.IsChecked!=true||Roots.Items.Count==0)throw new InvalidOperationException("검사 폴더를 선택하고 동의해 주세요.");if(report!=null)throw new InvalidOperationException("다시 검사하려면 새 코드를 발급받아 주세요.");ProgressTitle.Text="파일과 실행 흔적을 검사합니다";ProgressCount.Text="검사 준비 중";Busy(true);cts=new();RefreshFlow();await api.Send<JsonElement>("POST",$"/api/player/{claim.Session.Id}/progress",new{stage="scanning",count=0},cts.Token);var roots=Roots.Items.Cast<string>().ToArray();var scope=claim.Session.Scope;var elevate=Elevate.IsChecked==true;var deletedHistory=DeletedHistory.IsChecked==true;var scanner=new Scanner(Scanner.LoadRules(Path.Combine(AppContext.BaseDirectory,"rules/catalog.json")));var preferences=SkipSystemStores.IsChecked==true?ScanPreferences.Recommended(SystemRoot):null;var progress=new Progress<ScanProgress>(ShowScanProgress);inspected=0;heartbeat=new(){Interval=TimeSpan.FromSeconds(10)};heartbeat.Tick+=async(_,_)=>{if(reporting)return;reporting=true;try{await api.Send<JsonElement>("POST",$"/api/player/{claim.Session.Id}/progress",new{stage="scanning",count=inspected});}catch{Status.Text="검사는 계속 진행 중입니다. 서버 진행 알림 연결을 확인해 주세요.";}finally{reporting=false;}};heartbeat.Start();
  report=await Task.Run(()=>scanner.ScanAsync(roots,scope,progress,cts.Token,preferences));
  var pathsById=scanner.LocalPaths.ToDictionary(p=>p.Value,p=>p.Key);var peIds=report.Chunks.SelectMany(c=>c.Files).Where(f=>f.Format=="pe").Select(f=>f.Id).ToHashSet();var tracePaths=scanner.LocalPaths.Where(p=>peIds.Contains(p.Value)).Take(20000).ToDictionary(p=>p.Key,p=>p.Value,StringComparer.OrdinalIgnoreCase);if(peIds.Count>20000)report.Chunks.Add(new([],[],[],[new("traces","partial","실행 파일 연결 한도 20,000개 초과",20000)]));if(!cts.IsCancellationRequested){Status.Text="서명·실행 흔적 확인 중";ShowFollowupProgress("서명·실행 흔적 확인 중");await VerifySignaturesAsync(report,pathsById,cts.Token);ShowFollowupProgress("실행 흔적 확인 중");
   if(scope.ExecutionTraces){TraceOutput traces;if(elevate){try{traces=await ElevatedTraces(tracePaths,roots,deletedHistory,scope,cts.Token);}catch(System.ComponentModel.Win32Exception){traces=await Task.Run(()=>Traces.Collect(tracePaths,cts.Token,roots,deletedHistory,scope));traces.Coverage.Add(new("elevation","denied","관리자 권한 요청 거부. 일반 권한 결과만 포함.",0));}}else traces=await Task.Run(()=>Traces.Collect(tracePaths,cts.Token,roots,deletedHistory,scope));foreach(var group in traces.Artifacts.Chunk(100))report.Chunks.Add(new([],group.ToList(),[],[]));report.Chunks.Add(new([],[],[],traces.Coverage));MergeDeletedFiles(traces);}
  }
  if(!cts.IsCancellationRequested&&scope.HardwareChanges){Status.Text="하드웨어·시스템 변경 흔적 확인 중";ShowFollowupProgress("시스템 변경 흔적 확인 중");var baseline=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Watchblock","hardware-baseline.json");var hardware=await Task.Run(()=>HardwareChecks.Collect(baseline,cts.Token));report.Chunks.Add(new([],hardware.Artifacts,hardware.Findings,hardware.Coverage));report=report with{Summary=report.Summary with{Review=report.Summary.Review+hardware.Findings.Count}};}
  heartbeat?.Stop();while(reporting)await Task.Delay(50);bool partial=report.Chunks.SelectMany(c=>c.Coverage).Any(c=>c.Status!="complete");report=report with{Summary=report.Summary with{Completion=cts.IsCancellationRequested?"cancelled":partial?"partial":report.Summary.Completion,Finished=DateTimeOffset.UtcNow.ToString("O")}};
  if(cts.IsCancellationRequested)terminal=true;ShowReport();try{await api.Send<JsonElement>("POST",$"/api/player/{claim.Session.Id}/progress",new{stage=cts.IsCancellationRequested?"cancelled":"awaiting-submit",count=report.Summary.Files});Status.Text=cts.IsCancellationRequested?"검사를 취소했습니다. 로컬 보고서를 저장할 수 있습니다.":"전송할 내용을 확인하고 보고서를 제출해 주세요.";}catch{Status.Text="검사 결과는 보관 중입니다. 인터넷 연결이 복구되면 보고서를 제출해 주세요. 로컬 저장도 가능합니다.";}
 }catch(OperationCanceledException){terminal=true;Status.Text="검사를 취소했습니다.";await NotifyTerminal("cancelled");}catch(Exception ex){terminal=true;Status.Text=ex.Message;await NotifyTerminal("failed");}finally{heartbeat?.Stop();cts?.Dispose();cts=null;Busy(false);if(report?.Summary.Completion=="cancelled")SubmitButton.IsEnabled=false;}}
 private async Task NotifyTerminal(string stage){try{if(api!=null&&claim!=null)await api.Send<JsonElement>("POST",$"/api/player/{claim.Session.Id}/progress",new{stage,count=report?.Summary.Files??0});}catch{Status.Text+=" 서버 상태 알림 실패. 로컬 결과를 보관해 주세요.";}}
 private static async Task<TraceOutput> ElevatedTraces(Dictionary<string,string> paths,string[] roots,bool deletedHistory,ScanScope scope,CancellationToken ct){string id=Guid.NewGuid().ToString();await using var pipe=new NamedPipeServerStream("watchblock-"+id,PipeDirection.InOut,1,PipeTransmissionMode.Byte,PipeOptions.Asynchronous|PipeOptions.CurrentUserOnly);using var child=Process.Start(new ProcessStartInfo(Environment.ProcessPath!,"--trace-pipe "+id){UseShellExecute=true,Verb="runas",WindowStyle=ProcessWindowStyle.Hidden})??throw new InvalidOperationException("보조 프로세스 실행 실패");using var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct);timeout.CancelAfter(TimeSpan.FromSeconds(100));await pipe.WaitForConnectionAsync(timeout.Token);using var writer=new StreamWriter(pipe,leaveOpen:true){AutoFlush=true};using var reader=new StreamReader(pipe,leaveOpen:true);await writer.WriteLineAsync(JsonSerializer.Serialize(new TraceRequest(paths,roots,deletedHistory,scope),Json.Options));var line=await reader.ReadLineAsync(timeout.Token);return JsonSerializer.Deserialize<TraceOutput>(line??"",Json.Options)??throw new InvalidOperationException("보조 검사 결과 없음");}
 private void ShowReport(){if(report==null)return;MetricFiles.Text=report.Summary.Files.ToString("N0");MetricKnown.Text=report.Summary.Known.ToString("N0");MetricReview.Text=report.Summary.Review.ToString("N0");MetricCoverage.Text=report.Chunks.SelectMany(c=>c.Coverage).Count(c=>c.Status!="complete").ToString("N0");ResultTitle.Foreground=new System.Windows.Media.SolidColorBrush(report.Summary.Known>0?System.Windows.Media.Color.FromRgb(255,125,141):System.Windows.Media.Color.FromRgb(234,240,250));ResultTabs.SelectedIndex=report.Summary.Known+report.Summary.Review+report.Summary.Policy>0?1:0;if(SystemParameters.ClientAreaAnimation)ResultPane.BeginAnimation(OpacityProperty,new System.Windows.Media.Animation.DoubleAnimation(0.3,1,TimeSpan.FromMilliseconds(220)));Files.ItemsSource=report.Chunks.SelectMany(c=>c.Files).ToList();Findings.ItemsSource=report.Chunks.SelectMany(c=>c.Findings).ToList();Artifacts.ItemsSource=report.Chunks.SelectMany(c=>c.Artifacts).ToList();Coverage.ItemsSource=report.Chunks.SelectMany(c=>c.Coverage).ToList();ResultTitle.Text=report.Summary.Known>0?"치트 프로그램이 발견되었습니다":report.Summary.Review>0?"검토할 항목이 있습니다":"검사 결과";ResultSummary.Text=$"파일 {report.Summary.Files:N0}개 · 치트 프로그램 {report.Summary.Known} · 검토 {report.Summary.Review} · 규정 {report.Summary.Policy}\n완료 상태: {DisplayStatus(report.Summary.Completion)}. 탐지 없음은 치트를 사용하지 않았다는 보증이 아닙니다.";}
 private static string DisplayStatus(string status)=>status switch{"complete"=>"완료","partial"=>"부분 완료","cancelled"=>"취소","failed"=>"실패",_=>status};
 private void Cancel_Click(object sender,RoutedEventArgs e)=>cts?.Cancel();
 private async void Export_Click(object sender,RoutedEventArgs e){
  if(report==null||working)return;string? temporary=null;
  try{
   var dialog=new SaveFileDialog{Filter="JSON 보고서|*.json",FileName="watchblock-report.json"};if(dialog.ShowDialog(this)!=true)return;
   var snapshot=report;temporary=dialog.FileName+"."+Guid.NewGuid().ToString("N")+".tmp";cts=new();ProgressTitle.Text="전체 보고서를 저장합니다";ProgressCount.Text="로컬 파일 작성 중";Busy(true);
   await Task.Run(async()=>{await using var stream=new FileStream(temporary,FileMode.CreateNew,FileAccess.Write,FileShare.None,65536,true);await JsonSerializer.SerializeAsync(stream,snapshot,Json.Options,cts.Token);},cts.Token);
   File.Move(temporary,dialog.FileName,true);temporary=null;Status.Text="전체 로컬 보고서를 저장했습니다.";
  }catch(OperationCanceledException){Status.Text="보고서 저장을 취소했습니다.";}catch(Exception ex){Status.Text="보고서 저장 실패: "+ex.Message;}
  finally{if(temporary!=null)try{File.Delete(temporary);}catch(IOException){}catch(UnauthorizedAccessException){}cts?.Dispose();cts=null;Busy(false);}
 }
 private async void Submit_Click(object sender,RoutedEventArgs e){if(api==null||claim==null||report==null)return;try{ProgressTitle.Text="보고서를 전송합니다";ProgressCount.Text="전송 준비 중";Busy(true);cts=new();RefreshFlow();var hashes=new List<string>();long bytes=0;int omitted=0;bool partial=false;var uploadChunks=UploadOrder.Prioritize(report);for(int i=0;i<uploadChunks.Count;i++){var chunk=uploadChunks[i];var length=System.Text.Encoding.UTF8.GetByteCount(JsonSerializer.Serialize(chunk,Json.Options));if(length>262144||bytes+length>10*1024*1024||hashes.Count>=1000){partial=true;omitted+=chunk.Files.Count;continue;}ProgressCount.Text=$"{i+1} / {report.Chunks.Count} 묶음";Status.Text=$"보고서 제출 · {i+1}/{report.Chunks.Count}";var response=await api.Send<JsonElement>("PUT",$"/api/player/{claim.Session.Id}/chunks/{hashes.Count}",chunk,cts.Token);hashes.Add(response.GetProperty("hash").GetString()!);bytes+=length;}
  var summary=report.Summary with{Submission=partial?"partial":"complete",Omitted=omitted};report=report with{Summary=summary};await api.Send<JsonElement>("POST",$"/api/player/{claim.Session.Id}/complete",new{summary,hashes},cts.Token);Status.Text=partial?"용량 제한으로 일부만 제출했습니다. 원본 보고서는 로컬에서 저장할 수 있습니다.":"보고서 제출 완료. 앱에서 확인한 결과를 운영자에게 전달했습니다.";terminal=true;DeleteButton.IsEnabled=true;
 }catch(Exception ex){Status.Text=ex is OperationCanceledException?"전송 중단. 다시 제출하면 동일 페이지부터 확인합니다.":ex.Message;}finally{cts?.Dispose();cts=null;Busy(false);}}
 private async void Decline_Click(object sender,RoutedEventArgs e){if(api==null||claim==null)return;try{await api.Send<JsonElement>("POST",$"/api/player/{claim.Session.Id}/progress",new{stage="declined",count=report?.Summary.Files??0});terminal=true;Status.Text="보고서 제출을 거부했습니다.";SubmitButton.IsEnabled=false;ScanButton.IsEnabled=false;DeclineButton.IsEnabled=false;RefreshFlow();}catch(Exception ex){Status.Text=ex.Message;}}
 private async void Delete_Click(object sender,RoutedEventArgs e){if(api==null||claim==null)return;if(MessageBox.Show(this,"서버의 검사 보고서를 삭제할까요?","보고서 삭제",MessageBoxButton.YesNo)!=MessageBoxResult.Yes)return;try{await api.Send<JsonElement>("DELETE",$"/api/player/{claim.Session.Id}");terminal=true;Status.Text="서버 보고서를 삭제했습니다.";SubmitButton.IsEnabled=false;DeleteButton.IsEnabled=false;RefreshFlow();}catch(Exception ex){Status.Text=ex.Message;}}
}

