// Local integration harness. Not imported by the deployed Worker; refuses non-loopback traffic.
import{createServer}from'node:http';import{DatabaseSync}from'node:sqlite';import{readFileSync,existsSync,mkdirSync}from'node:fs';import path from'node:path';import worker,{hash,type Env}from'../worker/index';
mkdirSync('.tools',{recursive:true});const db=new DatabaseSync('.tools/local.db');db.exec('PRAGMA foreign_keys=ON');if(!db.prepare("SELECT name FROM sqlite_master WHERE name='scans'").get())db.exec(readFileSync('migrations/0001_initial.sql','utf8'));
db.exec(readFileSync('migrations/0002_report_shares.sql','utf8'));
if(!db.prepare('PRAGMA table_info(report_shares)').all().some((c:any)=>c.name==='sections'))db.exec(readFileSync('migrations/0003_share_details.sql','utf8'));
if(!db.prepare("SELECT name FROM sqlite_master WHERE name='chunks_findings'").get())db.exec(readFileSync('migrations/0004_evidence_indexes.sql','utf8'));
const d1={prepare(sql:string){let values:any[]=[];const stmt={bind(...v:any[]){values=v;return stmt},async first(){return db.prepare(sql).get(...values)||null},async all(){return{results:db.prepare(sql).all(...values)}},async run(){const r=db.prepare(sql).run(...values);return{meta:{changes:Number(r.changes)}}}};return stmt}};
const key=crypto.randomUUID();db.prepare("INSERT OR IGNORE INTO operators VALUES('1','local-owner','owner',NULL)").run();db.prepare('INSERT INTO auth_sessions VALUES(?,?,?)').run(await hash(key),'1',Math.floor(Date.now()/1000)+86400);
const env={DB:d1, ENVIRONMENT:'development',PUBLIC_ORIGIN:'http://localhost:8787',OWNER_GITHUB_ID:'1',SERVICE_NAME:'Sentinel · 로컬 개발',ADMISSIONS_OPEN:'true',GITHUB_CLIENT_ID:'',GITHUB_CLIENT_SECRET:'',ASSETS:{async fetch(r:Request){const url=new URL(r.url);let filename=path.resolve('dist','.'+url.pathname);if(!filename.startsWith(path.resolve('dist')+path.sep)||!existsSync(filename)||url.pathname==='/')filename=path.resolve('dist/index.html');return new Response(readFileSync(filename),{headers:{'Content-Type':filename.endsWith('.js')?'text/javascript':filename.endsWith('.css')?'text/css':'text/html'}})}}}as unknown as Env;
const server=createServer(async(req,res)=>{try{if(!['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress||'')){res.writeHead(403).end();return;}if(!['localhost:8787','127.0.0.1:8787'].includes(req.headers.host||'')){res.writeHead(403).end();return;}if(req.url==='/dev/login'){const key=crypto.randomUUID();db.prepare('INSERT INTO auth_sessions VALUES(?,?,?)').run(await hash(key),'1',Math.floor(Date.now()/1000)+86400);res.writeHead(302,{'Set-Cookie':`wb_session=${key}; Path=/; HttpOnly; SameSite=Lax`,Location:'/'}).end();return;}let size=0;const chunks:Buffer[]=[];for await(const chunk of req){size+=chunk.length;if(size>300000){res.writeHead(413).end();return;}chunks.push(chunk);}const headers=new Headers();for(const[k,v]of Object.entries(req.headers))if(v)headers.set(k,Array.isArray(v)?v.join(','):v);const response=await worker.fetch(new Request(env.PUBLIC_ORIGIN+req.url,{method:req.method,headers,body:['GET','HEAD'].includes(req.method||'GET')?undefined:Buffer.concat(chunks)}),env);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch{res.writeHead(500).end('Local harness failed')}});
server.listen(8787,'127.0.0.1',()=>console.log('Local test login: http://localhost:8787/dev/login'));
