import {ThemeButton} from './Theme';
import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import type{ReportChunk,ScanSession}from'../shared/contracts';
import {ReportSharing,SharedReport} from './ReportSharing';
import {ReportHero} from './ReportHero';
import {InviteCard,PlayerInvitation} from './InviteCard';
import {request as api,ApiError,AppDownload,useService} from './Service';
import './style.css';
import './security-theme.css';
import './compact.css';
import './theme.css';
type Session=ScanSession&{chunkCount:number;receipt?:string};
const labels:Record<string,string>={files:'파일 목록',findings:'탐지 근거',artifacts:'실행·삭제 흔적',coverage:'검사 범위',error:'오류',skipped:'제외',changed:'변경됨',created:'코드 발급',claimed:'앱 연결',scanning:'검사 중','awaiting-submit':'제출 대기',uploading:'전송 중',submitted:'제출 완료',cancelled:'취소',declined:'제출 거부',failed:'실패',complete:'완료',partial:'부분 완료',known:'치트 프로그램',review:'검토 필요',policy:'서버 규정',denied:'권한 부족',unsupported:'미지원','no-action':'조치 없음','needs-review':'추가 검토','policy-violation':'규정 위반'};
const l=(s:string)=>labels[s]||({'recycle-bin':'휴지통',usn:'삭제 저널'} as Record<string,string>)[s]||s;
function App(){const {service,error:serviceError}=useService();const[allFiles,setAllFiles]=useState(true),[hardware,setHardware]=useState(true);const[query,setQuery]=useState(''),[filter,setFilter]=useState('all');const[user,setUser]=useState<{id:string;login:string;role:string}|null>(null),[loaded,setLoaded]=useState(false),[scans,setScans]=useState<Session[]>([]),[selected,setSelected]=useState<Session|null>(null),[tab,setTab]=useState('findings'),[chunk,setChunk]=useState<ReportChunk|null>(null),[page,setPage]=useState(0),[hasMore,setHasMore]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[code,setCode]=useState(''),[create,setCreate]=useState(false),[nickname,setNickname]=useState(''),[reason,setReason]=useState(''),[extra,setExtra]=useState(false),[traces,setTraces]=useState(true),[banned,setBanned]=useState(''),[note,setNote]=useState(''),[verdict,setVerdict]=useState('needs-review'),[operators,setOperators]=useState(false),[inviteId,setInviteId]=useState(''),[inviteLogin,setInviteLogin]=useState('');
 const refresh=async()=>setScans(await api('/api/scans'));
 const visibleScans=scans.filter(s=>(s.nickname+' '+s.reason).toLowerCase().includes(query.toLowerCase())&&(filter==='all'||(filter==='review'?s.state==='submitted'&&!s.review:s.state===filter)));
 useEffect(()=>{if(selected)document.querySelector('.detail')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})},[selected?.id]);
 useEffect(()=>{api<any>('/api/me').then(u=>{setUser(u);return refresh()}).catch(e=>{if(!(e instanceof ApiError&&e.status===401))setError(e.message)}).finally(()=>setLoaded(true));},[]);
 useEffect(()=>{if(!user||!scans.some(s=>['claimed','scanning','awaiting-submit','uploading'].includes(s.state)||(s.state==='created'&&Date.now()/1000-s.created<900)))return;let pending=false;const timer=setInterval(()=>{if(document.hidden||pending)return;pending=true;refresh().catch(e=>setError(e.message)).finally(()=>pending=false)},60000);return()=>clearInterval(timer)},[user,scans]);
 useEffect(()=>{if(!selected)return;const next=scans.find(s=>s.id===selected.id);if(next)setSelected(next)},[scans]);
 useEffect(()=>{let stale=false;setChunk(null);setHasMore(false);if(selected?.state==='submitted')api<{items:any[];hasMore:boolean}>(`/api/scans/${selected.id}/sections/${tab}?page=${page}`).then(d=>{if(!stale){setChunk({files:[],findings:[],artifacts:[],coverage:[],[tab]:d.items});setHasMore(d.hasMore)}}).catch(e=>{if(!stale)setError(e.message)});return()=>{stale=true}},[selected?.id,selected?.state,tab,page]);
 async function action(fn:()=>Promise<void>){setError('');setBusy(true);try{await fn()}catch(e){setError(e instanceof Error?e.message:'처리에 실패했습니다.')}finally{setBusy(false)}}
 const counters={pending:scans.filter(s=>['created','claimed','scanning','awaiting-submit','uploading'].includes(s.state)).length,review:scans.filter(s=>s.state==='submitted'&&!s.review).length,known:scans.reduce((n,s)=>n+(s.summary?.known||0),0)};
 return <div className="app"><header><a className="brand" href="/" aria-label="Sentinel 홈"><span className="mark">▦</span>Sentinel</a><span className="muted">Minecraft Java</span><ThemeButton/>{user&&<div className="account">{user.login}<button onClick={()=>action(async()=>{await api('/api/logout','POST');setUser(null);setScans([])})}>로그아웃</button></div>}</header>
 {!loaded?<main>연결 확인 중…</main>:!user?<main className="login"><div className="eyebrow">SENTINEL · MINECRAFT JAVA</div><h1>더 명확한 검사.<br/><span>근거 있는 판단.</span></h1><p>치트 파일, 오토클릭, 매크로와 실행 흔적을 확인하세요.</p>{(error||serviceError)&&<div className="error" role="alert">{error||serviceError}<button onClick={()=>location.reload()}>다시 연결</button></div>}{service&&!service.ready?<p className="error">운영자가 GitHub 로그인 설정을 준비 중입니다.</p>:<a className="primary" href="/auth/github">GitHub로 로그인</a>} <AppDownload/><p className="muted small">초대받은 운영자만 접근할 수 있습니다.</p></main>:<div className="workspace"><nav><span className="navlabel">워크스페이스</span><button className={!operators?'active':''} onClick={()=>setOperators(false)}>▤ 검사 관리</button>{user.role==='owner'&&<button className={operators?'active':''} onClick={()=>setOperators(true)}>운영자 초대</button>}<div className="navfoot">기본 보관 7일<br/>파일 원본 수집 안 함</div></nav><main className={selected&&!operators?'report-open':'dashboard-open'}>
 {service&&!service.admissionsOpen&&<div className="notice" role="status">새 검사 접수가 중지되어 있습니다. 기존 보고서는 계속 확인할 수 있습니다.</div>}{error&&<div className="error" role="alert">{error}<button aria-label="알림 닫기" onClick={()=>setError('')}>×</button></div>}
 {operators?<><h1>운영자 초대</h1><form className="panel form" onSubmit={e=>{e.preventDefault();action(async()=>{await api('/api/operators','POST',{id:inviteId,login:inviteLogin});setInviteId('');setInviteLogin('');setError('초대 정보를 저장했습니다.')})}}><label>GitHub 숫자 사용자 ID<input required value={inviteId} onChange={e=>setInviteId(e.target.value)} pattern="[0-9]+"/></label><label>GitHub 로그인 이름<input required value={inviteLogin} onChange={e=>setInviteLogin(e.target.value)}/></label><p className="muted">초대된 운영자는 자신이 만든 검사만 볼 수 있습니다.</p><button className="primary" disabled={busy}>검토자로 초대</button></form></>:<>
 <div className="heading"><div><div className="eyebrow">SECURITY CONSOLE</div><h1>검사 관리</h1><p className="muted small">검사 요청부터 결과 검토까지</p></div><button className="primary" disabled={service?.admissionsOpen===false} onClick={()=>{setCreate(true);setCode('')}}>＋ 검사 만들기</button></div>
 <div className="stats"><div><span>전체 검사</span><strong>{scans.length}</strong></div><div><span>진행·대기</span><strong>{counters.pending}</strong></div><div><span>검토 대기</span><strong>{counters.review}</strong></div><div><span>치트 프로그램 탐지</span><strong>{counters.known}</strong></div></div>
 {create&&<section className="panel"><div className="heading"><h2>새 검사</h2><button onClick={()=>setCreate(false)}>닫기</button></div>{code?<InviteCard code={code}/>:<form className="createform" onSubmit={e=>{e.preventDefault();action(async()=>{const result=await api<{code:string}>('/api/scans','POST',{nickname,reason,scope:{gameFiles:true,allFiles,hardwareChanges:hardware,extraFolders:extra||allFiles,executionTraces:traces,bannedModIds:banned.split(',').map(s=>s.trim()).filter(Boolean)}});setCode(result.code);await refresh()})}}><label>대상 닉네임<input required maxLength={40} value={nickname} onChange={e=>setNickname(e.target.value)}/></label><label>검사 사유<input required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>서버 금지 모드 ID <small>선택 · 쉼표로 구분</small><input value={banned} onChange={e=>setBanned(e.target.value)}/></label><div className="checks"><label><input type="checkbox" checked={allFiles} onChange={e=>setAllFiles(e.target.checked)}/>전체 파일·드라이브 검사</label><label><input type="checkbox" checked={hardware} onChange={e=>setHardware(e.target.checked)}/>하드웨어 변경 흔적</label><label><input type="checkbox" checked={traces} onChange={e=>setTraces(e.target.checked)}/>실행 흔적</label><label><input type="checkbox" checked={extra} onChange={e=>setExtra(e.target.checked)}/>추가 폴더 허용</label></div><button className="primary" disabled={busy}>코드 발급</button></form>}</section>}
 <section className="panel tablewrap"><div className="listtools"><h2>최근 검사</h2><button disabled={busy} onClick={()=>action(refresh)}>새로고침</button><input aria-label="검사 검색" placeholder="닉네임·사유 검색" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="검사 필터" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체 상태</option><option value="submitted">제출 완료</option><option value="scanning">검사 중</option><option value="review">검토 대기</option></select></div><table><thead><tr><th>대상</th><th>상태</th><th>탐지 요약</th><th>만든 시간</th><th/></tr></thead><tbody>{visibleScans.map(s=><tr key={s.id} className={selected?.id===s.id?'selected':''}><td><b>{s.nickname}</b><div className="muted small">운영자 입력</div></td><td><span className={`badge ${s.summary?.known?'known':''}`}>{l(s.state)}</span></td><td>{s.summary?`일치 ${s.summary.known} · 검토 ${s.summary.review} · 규정 ${s.summary.policy}`:'—'}</td><td className="muted">{new Date(s.created*1000).toLocaleString('ko-KR')}</td><td><button onClick={()=>{setSelected(s);setPage(0);setNote(s.review?.note||'');setVerdict(s.review?.verdict||'needs-review')}}>열기 →</button></td></tr>)}</tbody></table>{!visibleScans.length&&<div className="empty"><h2>{scans.length?'검색 결과가 없습니다':'아직 검사가 없습니다'}</h2><p>{scans.length?'검색어나 상태 필터를 바꿔 보세요.':'검사 코드를 발급해 플레이어에게 전달하세요.'}</p></div>}</section>
 {selected&&<section className="panel detail"><div className="heading"><div><h2>검사 보고서</h2><p className="muted">{selected.reason}</p></div><button onClick={()=>setSelected(null)}>← 검사 목록</button></div><ReportHero summary={selected.summary} nickname={selected.nickname} id={selected.id}/><div className="notice">{selected.summary?`${l(selected.summary.completion)} · ${selected.summary.files}개 파일 · ${selected.summary.submission==='partial'?'일부 제출':'전체 제출'}`:l(selected.state)}. 결과는 앱이 제출한 검사 기록이며 게임 내 치트 사용의 자동 판정이 아닙니다.</div><div className="tabs" role="tablist">{[['findings','탐지 근거'],['artifacts','실행·시스템 흔적'],['coverage','검사 누락']].map(([id,title])=><button role="tab" aria-selected={tab===id} className={tab===id?'active':''} key={id} onClick={()=>{setTab(id);setPage(0)}}>{title}</button>)}</div>
 {selected.state!=='submitted'?<p className="empty">보고서가 제출되면 내용을 확인할 수 있습니다.</p>:<><div className="pager"><span>{l(tab)} {page+1} 페이지</span><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>이전</button><button disabled={!chunk||!hasMore} onClick={()=>setPage(p=>p+1)}>다음</button></div>{!chunk?<p>불러오는 중…</p>:<div className="evidence">{tab==='findings'?chunk.findings.map((f,i)=><details className="finding-row" key={i}><summary><span className={'badge '+f.category}>{l(f.category)}</span><h3>{f.title}</h3><span className="expand-evidence">근거 ⌄</span></summary><div className="small muted">규칙: {f.ruleId}</div><ul>{f.evidence.map((e,i)=><li key={i}>{e}</li>)}</ul></details>):tab==='artifacts'?chunk.artifacts.map((a,i)=><article key={i}><b>{l(a.source)}</b><p>{a.path}</p><p>{a.note}</p><small>{a.time||'시간 미확인'} · {a.association}</small></article>):chunk.coverage.map((c,i)=><article key={i}><b>{c.collector} · {l(c.status)}</b><p>{c.reason}</p><small>{c.inspected}개 확인</small></article>)}{chunk[tab as keyof ReportChunk].length===0&&<p className="empty">이 묶음에는 해당 항목이 없습니다.</p>}</div>}<form className="reviewform" onSubmit={e=>{e.preventDefault();action(async()=>{await api(`/api/scans/${selected.id}/review`,'POST',{verdict,note});await refresh()})}}><h3>운영자 검토</h3><select aria-label="검토 판정" value={verdict} onChange={e=>setVerdict(e.target.value)}><option value="needs-review">추가 검토</option><option value="no-action">조치 없음</option><option value="policy-violation">규정 위반</option></select><textarea required maxLength={4000} aria-label="검토 의견" placeholder="판단 근거를 남겨 주세요" value={note} onChange={e=>setNote(e.target.value)}/><button className="primary" disabled={busy}>검토 저장</button></form></>}
 {selected.state==='submitted'&&<ReportSharing key={selected.id} id={selected.id}/>}<button className="danger" disabled={busy} onClick={()=>{if(confirm('이 검사와 보고서를 삭제할까요?'))action(async()=>{await api(`/api/scans/${selected.id}`,'DELETE');setSelected(null);await refresh()})}}>검사 삭제</button></section>}
 </>}
 </main></div>}</div>
}
function Router(){
 const [hash,setHash]=useState(location.hash);
 useEffect(()=>{const change=()=>setHash(location.hash);addEventListener('hashchange',change);return()=>removeEventListener('hashchange',change)},[]);
 const playerInvite=/^#scan=([A-Fa-f0-9]{12})$/.exec(hash);
 const sharedReport=/^#report=([a-f0-9]{64})$/.exec(hash);
 return sharedReport?<SharedReport key={sharedReport[1]} token={sharedReport[1]}/>:playerInvite?<PlayerInvitation code={playerInvite[1]}/>:<App/>;
}
createRoot(document.getElementById('root')!).render(<Router/>);
