import {useEffect,useState} from 'react';
export const sectionLabels:Record<string,string>={findings:'탐지 근거',files:'전체 파일 목록',artifacts:'실행·삭제 흔적',coverage:'검사 누락·범위'};
const labels:Record<string,string>={known:'치트 일치',review:'검토 필요',policy:'서버 규정',complete:'완료',partial:'부분 완료',denied:'권한 부족',unsupported:'미지원',failed:'실패',cancelled:'취소',skipped:'제외',changed:'검사 중 변경',error:'오류','recycle-bin':'휴지통',usn:'삭제 저널','path-only':'경로 일치','basename-only':'이름 일치',none:'연결 없음'};
const label=(s:string)=>labels[s]??s;
export function PublicDetails({token,sections}:{token:string;sections:string[]}){
 const [section,setSection]=useState(sections.includes('findings')?'findings':sections[0]),[page,setPage]=useState(0),[response,setData]=useState<{section:string;page:number;items:any[];hasMore:boolean}|null>(null),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();setData(null);setError('');fetch(`/api/shared/${token}?section=${section}&page=${page}`,{signal:abort.signal}).then(async r=>{const d=await r.json() as {items:any[];hasMore:boolean;error?:string};if(!r.ok)throw Error(d.error??'상세 조회 실패');setData({...d,section,page})}).catch(e=>{if(!abort.signal.aborted)setError(e.message)});return()=>abort.abort()},[token,section,page]);
 const data=response?.section===section&&response.page===page?response:null;
 return <section className="public-details"><nav aria-label="공개 보고서 항목">{sections.map(s=><button key={s} aria-pressed={s===section} onClick={()=>{setSection(s);setPage(0)}}>{sectionLabels[s]}</button>)}</nav><div className="public-records" aria-busy={!data&&!error}>{error?<p role="alert">{error}</p>:!data?<p role="status">항목을 불러오는 중…</p>:!data.items.length?<p>공개된 기록이 없습니다. 미검사 항목은 검사 범위에서 확인하세요.</p>:data.items.map((v,i)=><details className="public-record" key={`${section}-${page}-${i}`} open={section==='coverage'}><summary><span className={`badge ${v.category??v.status??''}`}>{label(v.category??v.status??v.source)}</span><strong>{v.title??v.path??v.collector}</strong><span>{section==='files'?`${Number(v.size).toLocaleString()} B`:v.time?new Date(v.time).toLocaleString():section==='coverage'?`${v.inspected}개`:''}</span></summary><div className="public-evidence">{section==='files'?<><p>형식: {v.format} · 서명: {v.signature||'미수집'}</p><code>SHA-256: {v.sha256||v.hashReason||'미수집'}</code>{v.hashReason&&<p>{v.hashReason}</p>}{v.modIds.length>0&&<p>모드 ID: {v.modIds.join(', ')}</p>}</>:section==='findings'?<><small>{v.ruleId}</small>{v.evidence.map((e:string,n:number)=><p key={n}>{e}</p>)}{v.source&&<a href={v.source} target="_blank" rel="noreferrer">규칙 출처 ↗</a>}</>:section==='artifacts'?<><p>{v.note}</p><small>{label(v.association)} · 과거 파일과 현재 파일의 내용 동일성 미확인</small></>:<p>{v.reason}</p>}</div></details>)}</div><div className="public-pager"><button disabled={page===0||!data} onClick={()=>setPage(p=>p-1)}>← 이전</button><span>{page+1} 페이지 · 최대 100개</span><button disabled={!data?.hasMore} onClick={()=>setPage(p=>p+1)}>다음 →</button></div></section>;
}
