import {ThemeButton} from './Theme';
import {useEffect,useState} from 'react';
import {PublicDetails,sectionLabels} from './PublicDetails';
const labels:Record<string,string>={complete:'완료',partial:'부분 완료',cancelled:'취소','no-action':'조치 없음','needs-review':'추가 검토','policy-violation':'규정 위반'};
export function ReportSharing({id}:{id:string}){
 const [url,setUrl]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[hours,setHours]=useState(168),[sections,setSections]=useState<string[]>([]);
 async function act(method:string){setBusy(true);setMessage('');try{const r=await fetch(`/api/scans/${id}/share`,{method,headers:{'Content-Type':'application/json'},body:method==='POST'?JSON.stringify({publishSummary:true,hours,sections}):undefined});const d:any=await r.json();if(!r.ok)throw Error(d.error||'공유 설정 실패');setUrl(d.url||'');setMessage(method==='POST'?`만료: ${new Date(d.expires*1000).toLocaleString()}. 이전 링크는 폐기됩니다.`:'공유 링크를 철회했습니다.');}catch(e){setMessage(e instanceof Error?e.message:'공유 설정 실패');}finally{setBusy(false)}}
 return <details className="panel"><summary>공개 보고서 공유</summary><p>기본은 결과 요약입니다. 추가로 공개할 항목을 선택하세요. 닉네임·사유·검토 의견은 공개하지 않습니다.</p><div className="share-sections">{Object.entries(sectionLabels).map(([key,title])=><label key={key}><input type="checkbox" checked={sections.includes(key)} onChange={e=>{setSections(s=>e.target.checked?[...s,key]:s.filter(v=>v!==key));setConsent(false)}}/>{title}</label>)}</div>{sections.length>0&&<p className="muted">선택한 항목의 파일명·해시·근거가 누구에게나 공개됩니다. 개인 경로는 마스킹됩니다.</p>}<label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>링크를 가진 누구나 선택한 정보를 볼 수 있음을 확인했습니다.</label><div className="share-options"><label>공개 기간<select value={hours} onChange={e=>setHours(Number(e.target.value))}><option value={24}>1일</option><option value={72}>3일</option><option value={168}>7일</option></select></label><small>보고서 보관 만료까지만 공개됩니다.</small></div><div className="invite-actions"><button disabled={busy||!consent} onClick={()=>act('POST')}>공유 링크 만들기</button><button disabled={busy} onClick={()=>act('DELETE')}>공유 중지</button></div>{url&&<input aria-label="공개 보고서 링크" readOnly value={url} onFocus={e=>e.target.select()}/>}<p role="status">{message}</p></details>;
}
export function SharedReport({token}:{token:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();fetch('/api/shared/'+token,{signal:abort.signal}).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error||'조회 실패');setData(d)}).catch(e=>{if(!abort.signal.aborted)setError(e.message)});return()=>abort.abort()},[token]);
 return <div className="app"><header><a href="/" className="brand">▦ Sentinel</a><span>공개 검사 보고서</span><ThemeButton/></header><main className="panel public-report"><h1>검사 보고서</h1>{error?<p role="alert">{error}</p>:!data?<p>보고서를 불러오는 중…</p>:<><div className="stats"><div><span>검사 파일</span><strong>{data.files.toLocaleString()}</strong></div><div><span>치트 일치</span><strong>{data.known}</strong></div><div><span>검토 필요</span><strong>{data.review}</strong></div><div><span>서버 규정</span><strong>{data.policy}</strong></div></div><p>검사: {labels[data.completion]||data.completion} · 제출: {labels[data.submission]||data.submission} · 미제출 파일: {data.omitted}</p><p>운영자 판정: {labels[data.verdict]||'검토 전'}</p><p>만료: {new Date(data.expires*1000).toLocaleString()}</p><p className="muted">파일 발견은 게임에서의 사용 증거와 다릅니다. 탐지 없음은 무결함 보증이 아닙니다. {data.sections?.length?'운영자가 공개한 항목만 표시합니다.':'상세 항목을 공개하지 않은 요약 보고서입니다.'}</p>{data.sections?.length>0&&<><p className="muted">규칙 {data.ruleVersion} · {new Date(data.started).toLocaleString()} ~ {new Date(data.finished).toLocaleString()}</p><PublicDetails token={token} sections={data.sections}/></>}</>}</main></div>;
}
